version = 0.1

[default.deploy.parameters]
stack_name = "tts-zara-app"
resolve_s3 = true
s3_prefix = "tts-zara-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
